### ISSUE TITLE
Additional Item - Immersion Heater

### ISSUE THREAD

**Issue by redgs** [theodi/BDNS#105]
Immersion Heater – I was going to suggest IWH but this is already listed for an **Instant water heater.**
Can an Immersion Heater share the same or suggest a new one **IMWH**?

**Comment by RitaLav** [comment]
In addition to IWH, we would suggest taking a look at HWC, DEWH and DGWH.

We will go ahead and close the issue now - please reopen it if the above do not cover the requirement.
