### ISSUE TITLE
Additional Abbreviations

### ISSUE THREAD

**Issue by john-c-OSS** [theodi/BDNS#106]
Hi, are you able to check/ confirm the below new abbreviations please?

- Firemans Override Switch - suggest FMO - A fireman's override is a switch or input that allows the fire service to take control of those variable speed drives controlling fans to help maintain escape routes. Fire mode. Triggered by a special key at the fireman's control station, fire mode overrides all other inputs.
- Electric Heater Battery - suggest EHB - Electric heater batteries comprise sheathed type heating elements constructed from spirally wound nickel chromium resistance wire, insulated by compacted magnesium oxide powder and housed within stainless steel tubes.
- High Temperature Cut Out Switch - suggest HTCO - The term “Thermal Cutoff Switch” generally refers to how the switch is used, ie. It cuts off the current to critical machinery when a temperature limit is exceeded preventing potential burn out or failure.

**Comment by RitaLav** [comment]
Added to abbreviations register - included in pull request #146
