### ISSUE TITLE
Heat Pump Components

### ISSUE THREAD

**Issue by Beaneebar** [theodi/BDNS#108]
Suggestion for the addition of buffer tanks to be included with heat pumps

i.e. 
heat pump - cooling buffer 
heat pump - heating buffer 

Happy to follow the abbreviations as you see fit.

**Comment by Beaneebar** [comment]
^Update, perhaps recommend using abbreviations:
heat pump - cooling buffer -> HPCB
heat pump - heating buffer -> HPCB

**Comment by ocbark** [comment]
Does this need to be specific to a heat pump? I was thinking maybe making it a bit more broad so they could be used for multiple types of Buffer vessel independent of the system feeds them? Also maybe adding a generic? 

There are currently no buffer vessels described on the naming that I can see and the closest would be Thermal Storage Tank (TST).

BUFF - (Generic) Buffer Vessel
HBUFF - Heating Buffer Vessel
CBUFF - Cooling Buffer Vessel

**Comment by Beaneebar** [comment]
Very fair point and I would be a proponent of encouraging more generic terminology especially if the operation of the elements is essentially the same across different specific systems. 

I'm happy with what you suggest.

**Comment by pisuke** [comment]
Just to double check, is the suggestion to:
1. use TST for all these, or 
2. to introduce the three abbreviations?

**Comment by Beaneebar** [comment]
I think adding abbreviations for all of these would be the best approach.

**Comment by pisuke** [comment]
Addressed in #138
