### ISSUE TITLE
Standardized device naming

### ISSUE THREAD

**Issue by Beaneebar** [theodi/BDNS#109]
There is some inconsistency between how different devices are named. 

For example:
ahu - air handling unit , abbreviation 'ahu'
VS
heat pump - heat pump , abbreviation 'hp'

Can we standardize on a way of handling this? i.e.:
air handling unit - air handling unit , abbreviation 'ahu'
heat pump - heat pump , abbreviation 'hp'

**Comment by ocbark** [comment]
Agreed on this.
The abbreviation should be removed so as not to cause confusion.
AHU could be interpreted as both Air Handling Unit and Air Heating unit depending on your locale so should be specific.

**Comment by pisuke** [comment]
Addressed in PR #125
