### ISSUE TITLE
SIGD Project Asset Abbrevation Request

### ISSUE THREAD

**Issue by darshanjain12** [theodi/BDNS#113]
Hello, 

We at SIGD Gurgaon Project need to use this abbreviation for this equipment's .
Would be great if you would review these
1. Organic Waste Compactor Panel OWCP
2. Lift Well Pressurization fan LWPF
3. Lift Lobby Pressurization fan  LLPF
4.  Seismic Sensor SSS

**Comment by darshanjain12** [comment]
Hello Ocbark ,
Thank you for comments.
 Agreed will use WSTC for Organic Waste Compactor System.
For  both I also think that pressurization fan is what should be proposed.

 So to update what we would like to propose is

Pressurization fan  PF  HVAC/FAN IfcFan NOTDEFINED
Seismic Sensor SSS SENSOR IfcSensor NOTDEFINED

**Comment by pisuke** [comment]
Addressed in #138
