### ISSUE TITLE
Voice Alarm Panels (Racks, Repeaters, etc.)

### ISSUE THREAD

**Issue by dzikryazrul** [theodi/BDNS#131]
**device/asset description**
Voice Alarm Amplifier Racks, Main Panels and Repeater Panels 

**device/asset name**
VAP

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Comment by dzikryazrul** [comment]
here is a datasheet for an amp rack from Baldwin Boxall 

https://arup-my.sharepoint.com/:b:/p/dzikry_azrul/EZZ7nvt23sVJv7iXKOAJgCEBa3ESgl7VcKyhIKZPtRC0PQ?e=mkOnx7

if you need more info, please let me know :)

**Comment by RitaLav** [comment]
Is this the same as the suggestion for PAVA system discussed in #114

**Comment by jgunstone** [comment]
this PR https://github.com/theodi/BDNS/pull/174 (and associated issue https://github.com/theodi/BDNS/issues/132) integrated multiple abbreviations referrring to emergency voice communication - 

i think that the following satisfy your requirements: 

emergency voice communication - control panel | EVCCP
emergency voice communication - repeater unit | EVCRU

???

you are still missing Voice Alarm Amplifier Racks - 
though I wonder if the rack should just be a generic term that anything could be put in. 
e.g. https://www.rackyrax.com/2-compartment-ccs-colocation-server-racks/63880-43u-600mm-x-1000mm-2-compartment-colocation-server-rack.html

I just a quick look in the [BDNS_Abbreviations_Register.csv](https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv) and couldn't see anything for rack or cabinet.
