### ISSUE TITLE
Emergency Voice Communication (Panels - Main, Repeater, Sub)

### ISSUE THREAD

**Issue by dzikryazrul** [theodi/BDNS#132]
**device/asset description**
EVC devices (Panels - Main, Repeater, Sub)

**device/asset name**
EVCP 

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Comment by pisuke** [comment]
@dzikryazrul Can you please provide a working link for the type of product?

**Comment by dzikryazrul** [comment]
Hi sorry about this,

Main/repeater panels: https://www.baldwinboxall.co.uk/omnicare-master-control-panel/

Sub-panels: https://www.baldwinboxall.co.uk/omnicare-disabled-refuge/

**Comment by jgunstone** [comment]
disabled refuge systems are typically CDP (contractor design portion) items so aren't typically drawn schematically. 

some generic spec text: 

```
The system shall consist of:
- Two way Master Control Panels, identifying the status of all installed phones and reset panels 
- Two way addressable fire phone points and disabled refuges.
- “Loop powered” supply unit
- All required repeater panels.
```

Max Fordham typically uses DR for disabled refuge. 
and then an additional, different abbreviation for the control panel (as it is a different type of equipment). 
and maybe another one for repeater panels... my understanding breaks down - 

@dzikryazrul - can you clearly describe each of the different bits of equipment in the system ?

**Comment by jgunstone** [comment]
I had a look into this - 
I think we need some generic abbreviations, as well as some more specific ones for specific use cases (see Tank precendent) 

i.e.  DRO is a EVCO for a specific purpose - but the product type is slightly different

asset_description | asset_abbreviation | dbo_entity_type | ifc_class | ifc_type | device_asset documentation
-- | -- | -- | -- | -- | --
emergency voice communication   - control panel | EVCCP |   | IfcAudioVisualAppliance | COMMUNICATIONTERMINAL | https://www.baldwinboxall.co.uk/omnicare-master-control-panel/
emergency voice communication   - outstation | EVCO |   | IfcAudioVisualAppliance | RECEIVER | https://www.baldwinboxall.co.uk/omnicare-combined-units/
emergency voice communication   - outstation disabled refuge | DRO |   | IfcAudioVisualAppliance | RECEIVER | https://www.baldwinboxall.co.uk/omnicare-disabled-refuge/
emergency voice communication   - outstation fire telephone | FTO |   | IfcAudioVisualAppliance | RECEIVER | https://www.baldwinboxall.co.uk/omnicare-fire-telephones/
emergency voice communication   - outstation emergency telephone | ETO |   | IfcAudioVisualAppliance | RECEIVER | https://www.baldwinboxall.co.uk/omnicare-emergency-steward-telephone/
emergency voice communication   - repeater unit | EVCRU |   | IfcAudioVisualAppliance | SWITCHER | https://www.baldwinboxall.co.uk/wp-content/uploads/OmniCare-repeater-unit-WEB.pdf
emergency voice communication   - Voice Alarm Speaker | VAS |   | IfcAudioVisualAppliance | SPEAKER | https://source.thenbs.com/product/voicealarmhornloudspeaker/tb1QkN11aLWX34JJCDeP7p/tb1QkN11aLWX34JJCDeP7p
emergency voice communication   - Voice Alarm Microphones | VAM |   | IfcAudioVisualAppliance | MICROPHONE | https://source.thenbs.com/product/bdm400intelligentpagingmicrophonebdm416/ie2S1yTvYLWytzupsPmPhy/ie2S1yTvYLWytzupsPmPhy
