### ISSUE TITLE
HV switch Abbreviation 

### ISSUE THREAD

**Issue by dzikryazrul** [theodi/BDNS#133]
**device/asset description**
HV switches in electrical substations. Differs from Switchgear

**device/asset name**
HVSW 

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Comment by pisuke** [comment]
@dzikryazrul Can you please provide a working link for the type of product?

**Comment by dzikryazrul** [comment]
Main page: https://www.eaton.com/gb/en-gb/catalog/medium-voltage-power-distribution-control-systems/xiria.html

Technical page: https://www.eaton.com/gb/en-gb/catalog/medium-voltage-power-distribution-control-systems/xiria.technical.html

**Comment by jgunstone** [comment]
ELSW exists - 
would this be sufficient ?

**Comment by RitaLav** [comment]
Closing issue based on ELSW response. If needed please go ahead and reopen
