### ISSUE TITLE
Power Factor Correction system

### ISSUE THREAD

**Issue by mariogino** [theodi/BDNS#136]
**device/asset description**
Power Factor correction system with remote controller

**device/asset name**
PFC

**device/asset documentation**

Power factor correction: 
https://www.se.com/uk/en/product/VLVAF2P03506AA/varset-capacitor-bank-auto-050kvar-dr38-with-incomer-cb-xxb-400v-50hz/?parent-subcategory-id=4310&range=61501-powerlogic-pfc-capacitor-banks-iec&selected-node-id=12146989683

Controller: 
https://www.se.com/ww/en/download/document/7EN02-0376-00/

**Comment by pisuke** [comment]
Addressed in #138
