### ISSUE TITLE
MVHR and MEV

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#144]
**Mechanical Ventilator with Heat Recovery**
![image](https://user-images.githubusercontent.com/21370980/203941981-58dcba45-358d-4239-9194-700e5e85958d.png)
intake, supply, extract, exhaust mechanical ventilation with heat recovery. does not contain active heating or cooling elements.

**MVHR**
Note - there is name overlap here with HRU (Heat Recovery Unit) which already exists in the register. 

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document: nuaire-MRXBOX-ECO2](https://www.nuaire.co.uk/documentstore/catalogue/MRXBOX-ECO2.pdf)

Whilst I note above that HRU could be also used, the term MVHR is standard industry parlance and is commonly used in relevant industry documentation:
- UK building regulations approved document F volume 1 dwellings
- [Good Practice Guide
MVHR for single dwellings](https://www.passivhaustrust.org.uk/UserFiles/File/Technical%20Papers/2018%20MVHR%20Good%20Practice%20Guide%20rev%201.2(1).pdf)
- [NHBC Standards](https://nhbc-standards.co.uk/8-services/8-3-mechanical-ventilation-with-heat-recovery/)

---

**MEV**
Mechanical Extract Ventilator
Note - FAN and various types of fan exist in the register

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document: nuaire-MEVDC](https://www.nuaire.co.uk/documentstore/catalogue/MEVDC.pdf)

MEV is also common industry parlance and is used in:
- UK building regulations approved document F volume 1 dwellings
---

I develop Engineering software for Environmental Design Consultancy Max Fordham. We are considering adoption of BDNS. In both of the examples above I note that possible alternatives may already exist in the register. We strongly support the principle of this initiative to standard abbreviations across the industry and acknowledge that in some cases it will result in a deviation from established norms within our business. At the same time, I hope that where an industry norm exists as in the cases above, BDNS is able to accomodate.

Many Thanks 

John

**Comment by RitaLav** [comment]
Hi John,

Thank you so much for contributing and adhering to all of the workflows, label assignment and pull request template. It is great to see this as well as the fact you are considering adoption of BDNS and support of overall principle.

**Comment by jgunstone** [comment]
Great, thanks for the update, i'll hang tight for now. cheers

**Comment by RitaLav** [comment]
The above abbreviations requests have been approved and pull request #145 merged
