### ISSUE TITLE
Gas Solenoid Valve

### ISSUE THREAD

**Issue by ocbark** [theodi/BDNS#148]
Hi,

We have a requirement for a Gas Solenoid Valve on a project.

Currently there is a water solenoid valve defined as SNV but no Gas Solenoid Valve. Suggest we either update the SNV to just be a generic solenoid valve to suit all types of solenoid or add another specifc tag for Gas Solenoid Valve as something like GSV or GSNV.

Since SNV is already defined as a safety cut off valve as its ifc class and type I would suggest we just remove the water from the description to make this apply to all solenoid valves?

Thanks,

Oli

**Comment by RitaLav** [comment]
Discussed in meeting 1-Feb - it is suggested that 'water' should be dropped from description.

**Comment by RitaLav** [comment]
Addressed in #153
