### ISSUE TITLE
type references, instance references and unique references

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#150]
Hi there, 

I'd like to seek some clarification / discussion about how the tags are expected to be used... 

This describes how a unique asset identifer is created for an item 
https://github.com/theodi/BDNS/blob/master/BDNS_Specification_naming_syntax.md#deviceasset-role-name-assetname

>Definition
>The device or asset role name is a human-generated identifier that is unique to the building. It combines a standard 
>abbreviation for device/asset types and a numerical ID that is unique to each specific device/asset.

My reading of this is that every unique device (even it is exactly the same product as a neighboring device), must have a unique reference. To give an example, a car-park lit by identical downlights which are all controlled in the same way would require each unique fitting to have a unique reference. Can you confirm that this is the correct interpretation? 

In practice, often specific types only get a unique reference.
See example attached a screenshot of a drawing: 

![image](https://user-images.githubusercontent.com/21370980/215091699-92d9dea3-9720-41b0-a014-c454f72c9ac8.png)

e.g. 
LL-02 = Linear Light, Type 2 (BDNS compliant = LT-2)
LL-02E = Linear Light, Type 2 (BDNS compliant = LT-2_E)
DL-03 = Down Light, Type 3 (BDNS compliant = LT-3_E)

a schedule of types would then accompany this drawing. 
this means from the drawing it is very clear what each fitting is.
If the type number currently shown was replaced with a unique reference there would be no way of know what type the fitting is by looking at the drawing. In addition, during the design stage of a project, keeping track of a unique reference of every light fitting would be a big headache with little benefits offered. 

An approach to add a unique reference at later stages in a project that is often implemented is: 
`[type_reference]-[instance_reference]=[unique_reference]`

so in the example screenshot above (starting in the left-hand corner), to extend the tag to identify unique light fittings we'd get: 
- LL-01-1E (BDNS compliant (if type added) = LT-1-1_E)
- LL-01-2 (BDNS compliant (if type added) = LT-1-2_E)
- LL-01-3E (BDNS compliant (if type added) = LT-1-3_E)

this is partially addressed here: 

>For practical reasons, at the discretion of the user and as long as there are no name clashes between devices in the same building, the digits forming the second part of the device role name can be assigned following spatial or discipline specific scoping methods. For instance, the lighting fixtures on zone 1 of level 3 of a 20 storey building can all share the same first part of the name LT-103#### and the subsequent integer numbers can be attributed incrementally.

which suggests that custom rules for identifier naming could be developed. 
though I think that this approach can still lead to confusion as if type and instance references are joined it could lead to naming confusion (i.e. is LT-111 type 11 instance 1 or type 1 instance 11?)

Has this been considered? 
Or am I suggesting something outside the scope of this document? 
My experience is that tagging systems need to be practically useful for humans if they have any hope of being adopted! 

thanks in advance

**Comment by jgunstone** [comment]
for those interested, I began implementing an approach to give BDNS compliant tag name, whilst picking up other indentification information that is typically tracked. 

```py
from pydantic import BaseModel, Field, validator
import typing as ty
from enum import Enum
from IPython.display import Markdown


class OptionalIdentifiers(str, Enum):
    level_code = "level_code"
    volume_code = "volume_code"
    function_code = "function_code"


class ConfigTag(BaseModel):
    include_optional_suffix: bool = True
    optional_label_suffix_from: ty.Optional[list[OptionalIdentifiers]] = (
        "level_code",
        "volume_code",
        "function_code",
    )
    type_instance_delimiter: str = "-"


class BaseTag(BaseModel):
    """these fields exist in Revit"""

    abbreviation: str
    type_reference: int = None
    instance_reference: int = None
    assembly_overide: str = None
    level_code: str = None
    volume_code: str = None
    function_code: str = None


class Tag(BaseTag):
    """these are the generated tag values"""

    config: ConfigTag = ConfigTag()
    unique_reference: int = None
    optional_label_suffix: str = None
    tag: str = None

    @validator("unique_reference", always=True)
    def _unique_reference(cls, v, values):
        typ_ref = values["type_reference"]
        delim = values["config"].type_instance_delimiter
        ins_ref = values["instance_reference"]
        return f"{str(typ_ref)}{delim}{str(ins_ref)}"

    @validator("tag", always=True)
    def _tag(cls, v, values):
        conf = values["config"]
        ref = f"{values['abbreviation']}-{str(values['unique_reference'])}"
        if conf.include_optional_suffix and values["optional_label_suffix"] is not None:
            return f"{ref}_{values['optional_label_suffix']}"
        else:
            return ref

    @validator("optional_label_suffix", always=True)
    def _optional_label_suffix(cls, v, values):
        tup = values["config"].optional_label_suffix_from
        if tup is not None:
            return "-".join([str(values[t]) for t in tup])
        else:
            return v


tag1 = Tag(
    config=ConfigTag(type_instance_delimiter=""),
    abbreviation="DB",
    type_reference=12,
    instance_reference=1,
    level_code="L1",
    volume_code="B1",
    function_code="LTHW",
)

tag2 = Tag(
    config=ConfigTag(type_instance_delimiter="-"),
    abbreviation="DB",
    type_reference=12,
    instance_reference=1,
    level_code="L1",
    volume_code="B1",
    function_code="LTHW",
)


def display_tag(
    tag,
    title="title",
):
    s = "`" * 3
    return display(
        Markdown(
            f"""
{title}

**{tag.tag}**

{s}json
{tag.json(indent=4)}
{s}
"""
        )
    )


display_tag(
    tag1,
    title="### Example1: BDNS Compliant."
    "\n\n*Impossible to resolve type vs instance indentifer from number. Could easily lead to duplicate tags.*",
)
display_tag(
    tag2,
    title="### Example2: Not BDNS Compliant."
    "\n\n*Simple to resolve type vs instance indentifer from number. Maintains uniqueness.*",
)
```


![image](https://user-images.githubusercontent.com/21370980/215118228-39b3a943-7efe-412c-91ed-93a93b627304.png)

![image](https://user-images.githubusercontent.com/21370980/215118288-3d100534-1c17-4d4c-8a90-b5f86435bc72.png)

**Comment by RitaLav** [comment]
As per meeting discussion last week: The suggested method is to use either the suffix to define the type of instances or to assign 'meaning' to the digits (numerical part) in a company or project specific -approach (eg second digit corresponds to floor level or type of fitting etc)
