### ISSUE TITLE
non-unique asset type references

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#151]
hi there, 

i created this issue:
https://github.com/theodi/BDNS/issues/150
which has lots of commentary (too much commentary!). 

So I thought I would try and simplify. 

Is there a method or supported workflow for "Type" references? 
i.e. 
LT-1
where LT-1 is the type of light fitting (i.e. same model reference from the factory), of which there are many of the same type in the project? 

see image (LL = LT) 
![image](https://user-images.githubusercontent.com/21370980/215091699-92d9dea3-9720-41b0-a014-c454f72c9ac8.png)

**Comment by RitaLav** [comment]
Would you mind joining a call to quickly discuss this?

**Comment by jgunstone** [comment]
absolutely - apologies, only just spotted this

**Comment by RitaLav** [comment]
No problem - would you be available on Wednesday, 8 February · 4:00 – 4:30pm? Call link: https://meet.google.com/hog-ssqk-yvq

**Comment by jgunstone** [comment]
hi there - yes that works well - thanks

**Comment by RitaLav** [comment]
As per meeting discussion last week: The suggested method is to use either the suffix to define the type of instances or to assign 'meaning' to the digits (numerical part) in a company or project specific -approach (eg second digit corresponds to floor level or type of fitting etc)
