### ISSUE TITLE
Add'l shade and drape abbreviations for motor and control panel

### ISSUE THREAD

**Issue by mariehunter-bim** [theodi/BDNS#159]
**device/asset description**
We currently have abbreviation "SDC" for Shade and Drape Controller but need additional to go with that asset type

**device/asset name**
I propose that these be added:
"SDM" for Shade and Drape Motor
"SDCP" for Shade and Drape Control Panel
"SDSTM" for Shade and Drape Solar Tracking Module

**device/asset documentation**
https://embed.widencdn.net/pdf/view/springswindowfashions/szc9p5lcoh/26%2009%2040%20Automated%20Window%20Shade%20Specification.doc?u=7iwxok

**Comment by RitaLav** [comment]
The request for additional items makes sense.
Would suggest a slightly different asset description to align with the existing abbreviations
'shading-shading/blinds/drapes motor' 
'shading-shading/blinds/drapes conrol panel' 
'shading-shading/blinds/drapes solar tracking module' 

Would also suggest amending asset description for SDC from 'controller - shading device controller' to 'shading-shading/blinds/drapes controller' 

![image](https://github.com/theodi/BDNS/assets/59826095/ecd62ce7-8de2-4487-a378-6cd0faccffb1)

**Comment by mariehunter-bim** [comment]
Thank you for suggesting these add'l abbreviations. Description also LGTM.







Marie Hunter  |  LEED AP BD&C  |  BIM Facilitator

Working for Avixi at Google

CA, USA  |  408-592-1610
* * * * * * *  OOO - Vacation from June 5th to June 19th  * * * * * * *
