### ISSUE TITLE
Abbreviations needed for submetering

### ISSUE THREAD

**Issue by mariehunter-bim** [theodi/BDNS#171]
I would like to suggest the following submetter abbreviation types:
ESM for Electric Submeter
FSM for Flow Submeter
GSM for Gas Submeter
HSM for Heater Submeter
WSM for Water Submeter

**Comment by RitaLav** [comment]
Could you provide more information on why the differentiation between meter or submeter is needed as part of the asset abbreviation/name?
Typically this information could be included as part of the device/asset metadata. 
Is there a specific requirement/use case for this?

**Comment by mariehunter-bim** [comment]
Good point. We will be tracking the submeter now as part of the device
metadata.







Marie Hunter  |  LEED AP BD&C  |  BIM Facilitator

Working for Avixi at Google

CA, USA  |  408-592-1610
* * * * * * *  OOO - Vacation from June 5th to June 19th  * * * * * * *
