### ISSUE TITLE
request for BCBOX - Branch Controller Box

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#173]
**device/asset description**
used in VRF / VRV systems to control refrigerant flow across multiple branches. 

The function is the same. 
I've suggested BCBOX but we could add both ? 

**device/asset name**
Mitsubishi use the terminology BCBOX (Branch Controller Box)
Daikin use the terminology BSBOX (Branch Selector Box) 

**device/asset documentation**

mitsubishi
https://les.mitsubishielectric.co.uk/products/air-conditioning/city-multi-vrf/bc-controller-vrf

daikin
https://www.daikin.co.uk/en_gb/products/product.html/BS-Q14AV1B.html

**Comment by RitaLav** [comment]
One suggestion would be to add a single abbreviation, with a description that suits both
