### ISSUE TITLE
abbreviation required for battery trip unit

### ISSUE THREAD

**Issue by MarioG85** [theodi/BDNS#178]
**device/asset description**
Battery trip unit that is required to supply ELV euipment within LV switchboards (PLC, motorised breakers, etc.)

**device/asset name**
BTU

**device/asset documentation**
[https://www.pbdesign.co.uk/products/s2-battery-charger-dc-switch-tripper/21/](url)
![MicrosoftTeams-image (4)](https://github.com/theodi/BDNS/assets/66825397/fc97c139-1fdc-41cc-81b7-c94d5084c215)

**Comment by RitaLav** [comment]
BTR to be added
