### ISSUE TITLE
Lighting fitting type abbreviations

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#181]
on lighting drawings it is customary to have different abbrevations for different light fitting types. This makes drawings more readable. 

currently the only light fitting type in BDNS is:
LT: lighting - lighting fixture

## Suggested Abbreviations 

asset_description | asset_abbreviation | dbo_entity_type | ifc_class | ifc_type
-- | -- | -- | -- | --
lighting fixture - downlight | DL | LIGHTING/LT | IfcLightFixture | NOTDEFINED
lighting fixture - linear | LL | LIGHTING/LT | IfcLightFixture | DIRECTIONSOURCE
lighting fixture - linear tape | TL | LIGHTING/LT | IfcLightFixture | DIRECTIONSOURCE
lighting fixture - pendant | PL | LIGHTING/LT | IfcLightFixture | POINTSOURCE
lighting fixture - uplight | UL | LIGHTING/LT | IfcLightFixture | NOTDEFINED
lighting fixture - wall light | WL | LIGHTING/LT | IfcLightFixture | NOTDEFINED
lighting fixture - spot light | SL | LIGHTING/LT | IfcLightFixture | POINTSOURCE
lighting fixture - standalone emergency   light | EL | LIGHTING/LT | IfcLightFixture | NOTDEFINED
lighting fixture track - electric track for lights | TR | LIGHTING/LT | IfcCableSegment | NOTDEFINED
lighting fixture external - bollard | LBO | LIGHTING/LT | IfcLightFixture | NOTDEFINED
lighting fixture external - lampost | LPO | LIGHTING/LT | IfcLightFixture | NOTDEFINED

**Notes following discussion with MXF lighting team**
- lighting drawings contain a very high density of products compared with other drawings in the M&E package (see image)
- therefore limiting the abbreviation to as few characters as possible can really improve drawing legibility 
  - this has been taken into account with the abbreviations above
- there is also a precendent for the logic applied above with pump: 
  - e.g. PMP - Pump , DP - Dosing Pump, FHP - pump - fire hydrant pump etc.

**example busy lighting drawing**
![image](https://github.com/theodi/BDNS/assets/21370980/c5fc89d4-f526-4102-9d73-20819354a906)
^ it is noted that this drawing can be improved by adjusting the scale but it demonstrates the point. its a 1:100 dwg @ A1, but the text size is chosen to be legible when printed at A3

**Comment by RitaLav** [comment]
Feedback from Arup colleagues is that we would typically use LT-xxxxxx_luminaire type reference, which refers to the luminaire schedule that describes the luminaire type, so we would be unlikely to use the additional abbreviations.
Could still be added if useful to others.
