### ISSUE TITLE
CU - Consumer Unit

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#186]
**device/asset description**
consumer unit
practically its a distribution board but it is smaller; typicall used in houses and flats where a full DB isn't required. 
consumer unit is a commonly used term and it provides a useful distinction between larger distribution equipment (i.e. DB, PB) 

**device/asset name**
 CU

**device/asset documentation**
https://www.screwfix.com/p/mk-sentry-21-module-12-way-populated-dual-rcd-consumer-unit-with-spd/504pf

**Comment by pisuke** [comment]
If we decide to add it, I think it would be best to call it DBCU.

**Comment by jgunstone** [comment]
I reviewed this with the head of Electrical at MF and they didn't like the idea of DBCU, simply because it is different from the term that is already widespread used in the industry.

i also note that CONSUMERUNIT is an enum value in [IfcElectricDistributionBoardTypeEnum](https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcelectricaldomain/lexical/ifcelectricdistributionboardtypeenum.htm)

**Comment by RitaLav** [comment]
Distribution board is not describing the asset accurately, therefore it makes sense to have a different type of abbreviation

**Comment by ocbark** [comment]
My 2 cents - 
I would go with CU.
I feel that a consumer unit is more end user / domestic and therefore far enough away from a distribution board to not need the DB on the front. Also CU is a widely accepted term in the industry.
