### ISSUE TITLE
RAD, ERAD radiators

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#187]
**device/asset description**
radiators and electric radiators. 

**device/asset name**
RAD, ERAD

**aside**
this would compliment other terms that already exist in the database.
generally speaking, it would be possible to use HTR for RAD... but given that a radiator is probably the most common device for heat emission I think it warrants a specific and commonly used term.

![image](https://github.com/theodi/BDNS/assets/21370980/5b33af10-6d61-4b1e-8d0d-3e7608910442)

**Comment by pisuke** [comment]
It looks fine and useful to me.
