### ISSUE TITLE
Abbreviation needed for Battery Energy Storage System

### ISSUE THREAD

**Issue by mariehunter-bim** [theodi/BDNS#193]
I would like to propose abbreviation BESS for Battery Energy Storage System. This is a industry used abbreviation for assets such Tesla Megapacks

**device/asset documentation**
https://www.tesla.com/megapack
https://impulsoragdl.com/wp-content/uploads/2020/09/Ficha-Tecnica-Mega-Pack.pdf

**Comment by RitaLav** [comment]
Is the intention to tag/identify the whole system, or some components in it (eg one bank = 1 asset)?

**Comment by mariehunter-bim** [comment]
The intent would be to tag each preassembled packs or banks







Marie Hunter  |  LEED AP BD&C  |  BIM Facilitator

Working for Avixi at Google

CA, USA  |  408-592-1610

**Comment by pisuke** [comment]
I think we could use the already existing `BATT` abbreviation. Thoughts?

**Comment by mariehunter-bim** [comment]
I agree on keeping the use of BATT







Marie Hunter  |  LEED AP BD&C  |  BIM Facilitator

Working for Avixi at Google

CA, USA  |  408-592-1610
