### ISSUE TITLE
scope by authority rather than location

### ISSUE THREAD

**Issue by paulharter** [theodi/BDNS#20]
It would be more useful to scope the names with a naming authority rather than location ie :

`arup.com:ACU_001`

rather than 

`UK-LON-8FS_ACU_001`

The first is an an established methodology from urn/url naming and existing domains provide a ready way to implement this without additional discussion about naming conventions. Both approaches provide way to qualify the scope globally but using a location definition limits the activity of creating names to a single person/organisation/authority. It is much more useful and flexible to use authorities for scoping names as multiple actors can name objects that can then co-exist without risk of collisions. Location data is better provided by tag/metadata.

**Comment by pisuke** [comment]
Thanks for the suggestion!
Assets are scoped as unique within buildings / sites by their function within the building and not unique within organisations.
It is a different use case than, for instance, laptop devices withing a company, which is more similar to the use case you are describing.
