### ISSUE TITLE
[BOS Improvement] [Change Mgmt: NC Standards & Docs] ADD Entry for CRAH to go/bos-app19

### ISSUE THREAD

**Issue by John-Kazantzidis** [theodi/BDNS#214]
**device/asset description**
Computer Room Air Handler

**device/asset name**
CRAH

**device/asset documentation**
https://drive.google.com/file/d/1dBuR5vlnyEHBWHEbzhU5vy8lqnQ_t5fd/view?usp=drive_link&resourcekey=0--V0CWnu_sO6O1d3kKxs4FA

**Comment by John-Kazantzidis** [comment]
Thanks Rita, if you request access to the doc I can grant it. I will direct the team to proceed with CRAH unless I hear that it is not approved for some reason and we will pivot to something else.

**Comment by alnjxn** [comment]
next steps? Do we need a PR to close this out?

**Comment by RitaLav** [comment]
Yes please

**Comment by John-Kazantzidis** [comment]
Is there anything else needed from our team or are we ready to close this?

**Comment by alnjxn** [comment]
Hi @RitaLav sorry for the delay on this. see PR #222

**Comment by RitaLav** [comment]
abbreviation added as per #222
