### ISSUE TITLE
Add USS for Unit Substation

### ISSUE THREAD

**Issue by mariehunter-bim** [theodi/BDNS#217]
**device/asset description**
A unit substation consists of one or more transformers mechanically and electrically connected to and coordinated in design with one or more switchboard assemblies.

**device/asset name**
USS for Unit Substation

**device/asset documentation**
https://sandy.compas.siemens-info.com/compas-go-unit-substation-uss-switchgear-uss-switchboard_4682.html

**Comment by RitaLav** [comment]
Suggestion is acceptable.

Note: not a connected asset.
