### ISSUE TITLE
Add multisensor abbreviation

### ISSUE THREAD

**Issue by pisuke** [theodi/BDNS#22]
@DrOzakEsu commented in #4 about adding a multisensor abbreviation.
I've suggested to use *MTS* as the abbreviation for this. Any thoughts or comments?

**Comment by noursaidi** [comment]
I think MTS is good, my only question is whether we need to introduce an "environmental sensor" or similar, to avoid the scenario where all sensors become multi sensors. For example most room temperature sensors are also humidity sensors, will they be multi sensors too?

**Comment by pisuke** [comment]
It's a fundamental question. Do we aim for most generic approach, so MTS for all sensors, or do we specify based on discipline? @richardkreid any comments?

**Comment by pisuke** [comment]
Addressed in PR #62
