### ISSUE TITLE
pressure switch/sensor types

### ISSUE THREAD

**Issue by blip2** [theodi/BDNS#223]
I've had a request for the following additions from within one of our design teams:
TDSW – switch - thermal dispersion flow proving switch
DPX – sensor – differential pressure sensor
LPS – switch – low pressure switch
HPS – switch – high pressure switch

couple of points for discussion here:
- do we want to differentiate between a pressure sensor and switch. I would argue yes, physically and logically these are different things, former provides an analogue value, latter is boolean
- do we want to differentiate between low/high pressure. I would argue no, they are physically the same thing (except maybe N/C or N/O arrangement)
- thermal dispersion flow proving switch is probably a fair addition though quite specific - any thoughts?

**Comment by blip2** [comment]
also:
SPSW - Static Pressure Switch

**Comment by RitaLav** [comment]
Generally we do have both sensors and switches on bdns.

Some suggestions:

For differential pressure sensor maybe follow the abbreviation logic of the differential pressure switch (eg we can call the sensor DPRS)

TDSW - should be ok if needed/useful for project teams

SPSW - ok

![bdns](https://github.com/theodi/BDNS/assets/59826095/10ba8980-7e45-4633-8d7f-a07f2a732997)

Could you do a pull request for DPRS, SPSW and TDSW?

@pisuke @jgunstone any thoughts on high/low pressure switch discussion point raised (generic vs low/high pressure switch)?

**Comment by RitaLav** [comment]
on the last point, it was discussed today. Please add a generic pressure switch - PSW or PRSW (rather than adding low and high)

**Comment by RitaLav** [comment]
Will add:
sensor - differential pressure sensor,DPS,SENSOR,IfcSensor,PRESSURESENSOR
switch - differential pressure,DPSW,,IfcSwitchingDevice,NOTDEFINED
switch - absolute pressure,APSW, ,IfcSwitchingDevice,NOTDEFINED
switch - static pressure,SPSW, ,IfcSwitchingDevice,NOTDEFINED
switch - thermal dispersion flow proving switch,TDSW, ,IfcSwitchingDevice,NOTDEFINED

We will also need to amend the existing dew point switch abbreviation from 'DPSW' to 'DEWSW' and modify its ifc class to IfcSwitchingDevice

**Comment by RitaLav** [comment]
Pull request #224 merged.
