### ISSUE TITLE
EWH Electric Water Heater

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#235]
EWH Electric Water Heater

we already have DEWH (Domestic Electric Water Heater), but for a commercial project this is now needed. 
as a separate point, I'm not sure I understand the point of explicitly stating Domestic generally...? (for discussion at the next meeting) 

cheers

**Comment by RitaLav** [comment]
'Domestic' is typically related to the water system category (it is a 'type' of water system in Public Health). So it is applicable in commercial buildings too (another example would be 'non-potable' 'lab' 'cat5' etc etc

**Comment by RitaLav** [comment]
As discussed in weekly sync, EWH can be added in addition to DEWH. 

It can be discussed separately whether DEWH is still useful in the abbreviations register.

**Comment by jgunstone** [comment]
done https://github.com/theodi/BDNS/pull/244
