### ISSUE TITLE
VIC for Video Intercom

### ISSUE THREAD

**Issue by H-Rb** [theodi/BDNS#237]
**device/asset description**
Video Intercom 

**device/asset name**
VIC

**device/asset documentation**
https://www.commend.com/products/intercom/intercom-terminals-intercom-station-series-concerto-outdoor-stations-with-call-button-series-od1-200939/od1-cm.html

**Comment by RitaLav** [comment]
Would the existing abbreviation 'av equipment - audio video control keypad | AVKP' work for the use case?

**Comment by TheFridgeShaman** [comment]
VIC is currently being reviewed under #268. I'm closing this one, please refer to the other open issue.
Thanks.
