### ISSUE TITLE
CS for contact switch

### ISSUE THREAD

**Issue by H-Rb** [theodi/BDNS#239]
**device/asset description**
Contact set. To monitor door open/closed

**device/asset name**
CS

**device/asset documentation**
https://www.securitywarehouse.co.uk/catalog/intruder-alarm-c-36/door-contacts-switches-c-36_44/cqr-1-reed-4-core-pre-wired-surface-contact-p-4406.html

**Comment by TheFridgeShaman** [comment]
Duplicate of: sensor - contact sensor CNTS
Please use the above.
