### ISSUE TITLE
Request to add CAST as an approved asset acronym for: tank - compressed air storage

### ISSUE THREAD

**Issue by hunter-d-b** [theodi/BDNS#240]
**device/asset description**
A compressed air storage tank is used to store the output of an air compressor. An application typically includes a minimum of two compressed air storage tanks - a wet tank, and a dry tank. 

**device/asset name**
Device/asset name: tank - compressed air storage, Device/asset acronym: CAST

**device/asset documentation**
https://catalog.compressedairsystems.com/item/receiver-tanks/vertical-air-receivers-10-120-gallons/302414

**Comment by RitaLav** [comment]
We will add CAST to the register.
