### ISSUE TITLE
New Abbreviation Request for Branch Meter

### ISSUE THREAD

**Issue by pisuke** [theodi/BDNS#241]
**device/asset description**
Multi-circuit branch meter/branch monitor.
These meters are effectively acting as "gateways" to collect data from multiple circuit meters and aggregate them via BACnet, Modbus or other protocols.

**device/asset name**
BM (Branch Meter/Monitor) or MCBM (Multi Circuit Branch Meter/Monitor) or MCM (Multi Circuit Meter/Monitor)

**device/asset documentation**
* https://www.senvainc.com/en/products/energy-measurement/multi-circuit-(branch)-meter?offset=0&setSize=10
* https://www.dentinstruments.com/shop/power-meter/powerscout-12-hd-multi-circuit-power-submeter/

**Comment by RitaLav** [comment]
EBM (electrical branch meter) to be added to the register.

**Comment by richardkreid** [comment]
Excellent, glad to see added - EBM looks good to me.

**Comment by TheFridgeShaman** [comment]
Closed with addition of EBM - electric branch meter.
