### ISSUE TITLE
cables, data cables, pipework, ductwork

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#247]
The following have abbreviations for cables, data cables, pipework, ductwork have recently been requested. 

https://github.com/theodi/BDNS/issues/234
https://github.com/theodi/BDNS/issues/233
https://github.com/theodi/BDNS/issues/232
https://github.com/theodi/BDNS/issues/231
https://github.com/theodi/BDNS/issues/230
https://github.com/theodi/BDNS/issues/229
https://github.com/theodi/BDNS/issues/228

asset_description | asset_abbreviation | dbo_entity_type | ifc_class | ifc_type | can_be_connected
-- | -- | -- | -- | -- | --
electric distribution - coaxial cable | COAXCA |   | IfcCableSegment | NOTDEFINED | 0
electric distribution - data cable | DCCA |   | IfcCableSegment | NOTDEFINED | 0
electric distribution - fire rated cable | FCA |   | IfcCableSegment | NOTDEFINED | 0
electric distribution - cable | CA |   | IfcCableSegment | NOTDEFINED | 0
piped services - pipework | PW |   | IfcPipeSegment | NOTDEFINED | 0
ventilation - ductwork - fire rated | FDW |   | IfcDuctSegment | NOTDEFINED | 0
ventilation - ductwork | DW |   | IfcDuctSegment | NOTDEFINED | 0

At Max Fordham we have been using the BDNS standard for defining BIM objects in the model and producing equipment schedules. Every specified item in a schedule requires a unique reference (as described here: https://github.com/theodi/BDNS/blob/master/BDNS_Specification_naming_syntax.md#format-1). Although we wouldn't typically mark up a drawing with ductwork references (though perhaps sometimes, for special cases like ductwork with specific acoustic requirements in a concert hall), we do still need a unique reference to attach data to in our schedules. This lead us to request abbreviations for these items. It is acknowledged that these are not connected devices which was the original main BDNS use case... but they are items that we specify exactly on many projects, which is how we have been using BDNS on projects.

**Comment by RitaLav** [comment]
Makes sense as a use case. 

@pisuke?

**Comment by pisuke** [comment]
I think it would be useful to add the concept of `asset.type` in the specification, so this needs further discussion.

**Comment by RitaLav** [comment]
@jgunstone can we pick up this discussion next time you join the call?

**Comment by jgunstone** [comment]
following discussions last week - 
here is an example of how we use the abbreviation "PW" in equipment schedules to distinguish different types of pipework:
<img width="546" alt="image" src="https://github.com/user-attachments/assets/eaf571fd-f5d8-467b-bec7-ae9fe4f8d553">

in the BIM model the length of pipe would then be given a type reference `PW-1` for example. Many lengths of pipe in the model would be of type `PW-1` and there would be no expectation or requirement that every instance of pipe in the model would get its own unique reference
