### ISSUE TITLE
New asset - DX Coil

### ISSUE THREAD

**Issue by noursaidi** [theodi/BDNS#25]
I'd like to suggest a new abbreviation for a DXC - DX Reversible Coil

There is an abbreviation DXCC for DX cooling coil, but it is quite common for DX coils to be reversible and both heating and/or cooling. I've used these on several projects before, and the application is po

Technically, when heating the coil is "condensing" rather than "DX", but DX seems to be the accepted name for any refrigerant system

**Comment by pisuke** [comment]
@richardkreid I agree with this proposal, do you have any comments?

**Comment by RitaLav** [comment]
Add 'DXC' as an abbreviation
