### ISSUE TITLE
Smoke Vent verse Actuator

### ISSUE THREAD

**Issue by KenEnright** [theodi/BDNS#26]
Automatic heat and smoke vents are available commercially in two general categories. Concerning the scope of this effort, the mechanically opened vent, powered by springs, pneumatic actuator, or electric motors are of interest. The open/close state data point needs to attributed.

Should there be an abbreviation for automatic vents?

Note: we are aware of regional variations ie smoke extractor in Berlin.

**Comment by pisuke** [comment]
I've just merged #27 which adds the automatic smoke vent
