### ISSUE TITLE
Update abbreviations for tanks

### ISSUE THREAD

**Issue by RitaLav** [theodi/BDNS#263]
Update 

1) tank - break tank and booster set

From  BTBS to BRTBS

2)  tank - brine tank 

From BTK to BRITK

**Comment by RitaLav** [comment]
We will proceed as above.

**Comment by jgunstone** [comment]
proposed the minor variation: 

changes
`BTBS` -> `BTKBS`
`BTK` -> `BRITK`

addition
`BTK` = Break Tank
