### ISSUE TITLE
Intercom Systems

### ISSUE THREAD

**Issue by JimGriffin88** [theodi/BDNS#268]
Hi all, looking for abbreviations to cover the following:

Video Intercom
VIC
https://www.came.com/uk/installers/solutions/intercom-systems/entry-panels/xvp

Audio Intercom
AIC
https://www.came.com/uk/installers/solutions/intercom-systems/entry-panels/lhs-audio

Happy to discuss if anyone has found an alternative way to identify these items previously.

**Comment by TheFridgeShaman** [comment]
Hi Jim,
would you like to make a pull request with the addition of the above items?
Would you see them more fitting under AV equipment or Access Control?
The abbreviations have no clashes as they are, so we can keep them as proposed.

Thanks,
Andrea

**Comment by JimGriffin88** [comment]
Hi Andrea, apologies I've been on leave, in this instance there are specifically related to Access Control.
