### ISSUE TITLE
📚 build and serve latest version of BDNS website on Github pages

### ISSUE THREAD

**Issue by jgunstone** [theodi/BDNS#274]
we discussed a few weeks ago building more formal documentation using github pages. 
I just had a look at it and it was relatively painless to setup... 

see built GH pages on my fork here: https://jgunstone.github.io/BDNS/

it works as follows: 

- [x] rebuild on tag (release) 
- [x] build a pdf at the same time
- [x] uses the current tag to add the release to the build website / pdfs
  - this is the most complex bit... changing the source file within a GH action is tricky and should be avoided... 
  - but given that it rebuilds on release the `GITHUB_REF_NAME` is the tag name which is the version... so in the GH action I write a `version.md` file that is then referenced by the other files like this: `{{< include release.md >}}` at the moment it builds. This way the source files do not contain what release the repo is at, but the built pages and pdf files do. 
  - https://github.com/jgunstone/BDNS/blob/af300881c203b40ea19a10905a193ed98e97328d/.github/workflows/build-docs.yml#L14-L16

I think this would mean this PR needs updating as versioning would be removed from source files and would be automatic on tag/release: 
https://github.com/theodi/BDNS/pull/267

if people are happy with this approach its basically ready so I can make the PR.

**Comment by RitaLav** [comment]
@jgunstone please go ahead, we discussed today.

**Comment by jgunstone** [comment]
following today's meeting there are a couple of actions to improve the clarity of the BDNS website is presented to users who arrive at the Github page. 

- [ ] move the contents of the `README.md` file to the `index.qmd` file. 
- [ ] make the `README.md` simpler / dev focused and refer users to the main documentation. 

one issue that was raised maintaining a record of release history. 
every GH release will maintain a record of the source markdown files of past releases but won't keep they built website or pdfs. 
for the asset register csv file it is possible to retrieve this directly from past releases. 
it would definitely be possible to serve multiple versions... (e.g. https://github.com/koumoul-dev/gh-pages-multi) but it gets more complicated and I'm not sure I've got the time to look at this right now. 

I'd suggest that for now I'll just add some text to the readme: 

"
Currently we only serve the latest version of the BDNS built website and pdf documents.
The source markdown files of previous versions can reviewed by refering to the appropriate Github tag/release. 
The `BDNS_Abbreviations_Register.csv` file can also be retrieved directly from a previous tag/release if you are required to pin to a given version.
"
