### ISSUE TITLE
Add abbreviations for building elements

### ISSUE THREAD

**Issue by pisuke** [theodi/BDNS#28]
Room, floor, etc.

**Comment by garyedwards** [comment]
There are many places that could define base names for these abbreviations IFC etc.  [BOT](https://github.com/w3c-lbd-cg/bot) could be a good option as a simple ontology defining the core concepts of a building (Zone, Site, Building, Storey, Space etc.)

For more granular building elements that do not come under the `Device` category, are these in the scope of the project?  There are common abbreviations used in spec writing and on ASMEP drawings such as the table below.

I know Schumann use these abbreviations but do not believe it is unique to them.  It would be interesting to source a complete list if only as a reference and to avoid duplication if possible.  Or if this is in the scope of BDNS, adopting these abbreviation could be an option.

| Code      | Description |
| ----------- | ----------- |
| ALTERATIONS TO EXISTING WORKS   | ALT   |
| ARCHITECTURAL METALWORK   | AM   |
| BALUSTRADES/ HANDRAILS/ GUARDRAILS   | BAL   |
| CEILINGS   | CLG   |
| DOORS   | DRS   |
| EXPANSION JOINTS SYSTEMS   | EXJ   |
| EXTERNAL WALL SYSTEMS   | EWS   |
| FIXTURES/ FITTINGS/ EQUIPMENT/ FURNITURE   | FX   |
| FLOOR FINISHES   | FL   |
| GLAZED-IN PANELS   | GL   |
| INTERNAL WALL SYSTEMS   | IWS   |
| WALL FINISH LININGS   | LIN   |
| PAINT FINISHES   | PT   |
| PLASTERING   | PLS   |
| ROOF FINISH SYSTEMS   | RFS   |
| ROOFLIGHTS AND ROOF GLAZING SYSTEMS   | RFL   |
| SIGNAGE   | SGN   |
| UNFRAMED ISOLATED TRIMS/ SKIRTING/ SUNDRY ITEMS   | TRM   |

**Comment by pisuke** [comment]
The intent of BDNS is not to describe all the possible building components but just assets and devices to which data can be attached.
From the list provided, we already have DR for doors which makes sense (for instance information like open/close status can be attached to a door).
Possible we could include signage and furniture but the other components don't seem in scope to me.
