### ISSUE TITLE
Common Air Source Heat Pump Types - 2 Pipe Reversible, 4 Pipe Reversible, 4 Pipe Simultaneous/Polyvalent

### ISSUE THREAD

**Issue by Richard-Jackson-Arup** [theodi/BDNS#291]
**device/asset description**
heat pump - air source heat pump - 2 pipe reversible unit
heat pump - air source heat pump - 4 pipe reversible unit
heat pump - air source heat pump - polyvalent/simultaneous unit

**device/asset name**
2RHP
4RHP
PVHP

**device/asset documentation**
Provide link to a datasheet/manual/any supporting documentation
[example document](https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf)

**Comment by RitaLav** [comment]
@jgunstone @pisuke any thoughts on differentiating between 2 pipe and 4 pipe?

**Comment by RitaLav** [comment]
Noting the asset class doesn't change we would recommend to not increase the level of granularity.

@Richard-Jackson-Arup one way to deal with this is to add 'RHPTWO' or similar as an asset type, please see:  https://github.com/theodi/BDNS/blob/master/BDNS_Specification_naming_syntax.md#deviceasset-type-assettype

**Comment by Richard-Jackson-Arup** [comment]
Ok Rita, on reflection it is kind of easier to call all ASHPs the same thing given a typical project might have say 3 items of a total of 2 types.

I don't really understand the second comment about the RHPTWO.

**Comment by RitaLav** [comment]
Discussed in call.
