### ISSUE TITLE
Optional prefix standards

### ISSUE THREAD

**Issue by garyedwards** [theodi/BDNS#36]
Are there plans to include guidance for the optional prefix `<COUNTRY>-<CITY>-<BUILDING>`?  For example should country follow the [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes) codes.

When it comes to city and building it may be harder to recommended a convention as these become more region / organisation specific.

Feel free to close if this is outside of the scope of this project.

**Comment by pisuke** [comment]
This has been added already in version 1.0.0.
