### ISSUE TITLE
Lighting fixtures

### ISSUE THREAD

**Issue by KenEnright** [theodi/BDNS#37]
The abbreviations list has an abbreviation of LT. In the text, the [example](https://github.com/theodi/BDNS/blob/master/BDNS_Specification_naming_syntax.md#examples-1) shows LTF. What is the best approach so that projects have a primary option and align?

@pisuke - for visibility.

**Comment by pisuke** [comment]
Thanks @KenEnright,we'll keep LT as in the abbreviation list. Main document now updated.
There is also another change likely to happen to omit the leading 0 for the numbering.

**Comment by KenEnright** [comment]
Thanks for clarifying @pisuke.
