### ISSUE TITLE
Complete the abbreviation register

### ISSUE THREAD

**Issue by richardkreid** [theodi/BDNS#4]

**Comment by DrOzakEsu** [comment]
Abbreviation for multi-sensing devices is required. E.g. a sensor device that measures temperature, humidity, noise, CO2 and illuminance. Currently listed sensor abbreviations in the [register](https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv) relate to singular metrics e.g. Sensor - Light Motion sensor [LMS].

**Comment by pisuke** [comment]
Thank you @DrOzakEsu for the suggestion. We could add a new abbreviation **MTS** for a generic multisensor. We should try to avoid being too specific. @richardkreid any thoughts?

**Comment by pisuke** [comment]
Closing this issue as it was related to putting online the first draft.
