### ISSUE TITLE
Virtual points

### ISSUE THREAD

**Issue by drewdepriest** [theodi/BDNS#41]
Hi All,

Have you considered standards for naming virtual points in addition to physical devices and I/O?

Could be valuable to provide guidelines for elements like:

- **Setpoints**: heating/cooling with deadband, duct static, hydronic pressure, etc
- **Occupancy**: from schedule, physical sensor, and optimal start/stop routine
- **Calculated Values**: enthalpy, PUE, EUI, WUE, environmental index, calls for heat/cool, calls for static reset, VFD fan tracking, etc
- **Alarms**: various levels for maintenance up to critical

Cheers,
Drew

**Comment by pisuke** [comment]
Yes, this standard is only for asset/device instance naming and it is complementary to other standard like[ Brick Schema](https://brickschema.org/ontology/1.2) and [Digital Building Ontology](https://github.com/pisuke/digitalbuildings/blob/master/ontology/yaml/resources/fields/telemetry_fields.yaml) that specifically address ontology classes and data point naming.
As this is out of scope of the BDNS standard, I'm closing this issue.
