### ISSUE TITLE
Mechanical Heat Interface Unit's (HIU)

### ISSUE THREAD

**Issue by ocbark** [theodi/BDNS#44]
For buildings with Heat Interface Units HIU's between the landlord and tenant system mechanical systems what would we describe these as? These consist of a plate heat exchanger pump and valve. 

Is it possible to introduce an "HIU" tag to describe these or give guidance as to what they should be named? 
I cannot see a suitable mapping in the current published nametags list.

**Comment by RitaLav** [comment]
I suggest HIU to refer to it as a packaged system

**Comment by pisuke** [comment]
Addressed in #92
