### ISSUE TITLE
Socket Outlets - Abbreviations Register

### ISSUE THREAD

**Issue by Snoreledge** [theodi/BDNS#46]
Is there a way we can just simplify the below to something like 2 Gang and 1 gang Socket Outlet as ours are 13A here in the UK

And for floor box outlets if they contain data and power would this be covered under the floorbox Abbreviation?

  | outlet - double 20A duplex receptacle | DDR | IfcOutlet | POWEROUTLET
  | outlet - duplex outlets | DXO | IfcOutlet | POWEROUTLET

**Comment by blip2** [comment]
agreed, the number of outlets in a unit is important to know. having the where or what type/size is inconsistent with the rest of the abbreviations. e.g. BDNS doesn't differentiate between a wall mounted fan coil unit and ceiling mounted fan coil unit.
likewise with items like HVCPB and LVCPB which are oddly specific and not globally applicable.

**Comment by RitaLav** [comment]
Some additional thoughts from Arup electrical review:

![image (27)](https://user-images.githubusercontent.com/59826095/225618309-d32caf72-9bf1-4771-8134-91cc19355fc7.png)
