### ISSUE TITLE
Head End Server Name?

### ISSUE THREAD

**Issue by oli-barker** [theodi/BDNS#51]
We are looking to name and QR code Headend servers for Lighting and BMS systems.

Currently the nearest we can find that would fit this is HMI (Human Machine Interface) however this doesn't seem correct. Is this the correct tag to use or should we use another?

**Comment by john-c-OSS** [comment]
Hi all, I have the same requirement, has there been any update please?  The only other reference I have found is "data processing unit / computer - DPU" - But not sure if this is correct?
