### ISSUE TITLE
Additional Names - IoT Sensors

### ISSUE THREAD

**Issue by john-c-OSS** [theodi/BDNS#52]
Hi, we have some IoT sensors that need new abbreviations - would the below be ok?

- Indoor Air Quality  - propose IAQ
- Outdoor Air Quality – propose OAQ
- People Counting – PCS 
- Hot Tap point of use sensor – will use TPS
- E-ink display – propose EINKD 
- Tinkerforge desk sensor- propose DESKS
- User Feedback Button – propose UFB

**Comment by pisuke** [comment]
Thanks @john-c-OSS for the request.

About the air quality sensors, are the products you are describing only monitoring air quality or also other metrics?
The multisensor abbreviation MTS can cater for all the devices which aggregate different sensing types.
PCS already exists.
For e-ink displays, DS already exists.
I agree that a facilities/furniture asset for the desks is useful to aggregate data about the desks, which should be DESK, to be used for instance for desk booking and sensing use cases.
With the same spirit, an abbreviation for rooms like ROOM should be added.
User feedback buttons could probably be covered by a more generic entry for keypads, like KP.

**Comment by john-c-OSS** [comment]
Thanks for the feedback @pisuke  - noted on the above!

The air quality sensors monitor gases, particles, temperature and humidity - so do you think these are best classed as MTS?

**Comment by pisuke** [comment]
Yes, I think using MTS would make sense in this case.

**Comment by pisuke** [comment]
Final decision:

Indoor Air Quality - MTS
Outdoor Air Quality – MTS
People Counting – PCS
Hot Tap point of use sensor – TPS
E-ink display – propose DS
Tinkerforge desk sensor- DESK
User Feedback Button – KP
Combined Services Keypad (KNX) – KP
