### ISSUE TITLE
Abbreviations - IoT sensors/gateways

### ISSUE THREAD

**Issue by jameshare01** [theodi/BDNS#53]
Bin level sensor - proposed BINS-
Leak sensor - proposed LEAKS-
Movement sensor (accelerometer based) - proposed MOVES-
Door contact sensor - proposed CONTS-

**Comment by sicada** [comment]
1. I would suggest making a more generic entry, e.g. `sensor - level sensor (LVLS)`
2. This already exists as `sensor - leak detection sensor (LDS)`
3. A motion sensor (MOS) type already exists. If you want something for accelerometer-specific movement, then I would suggest we include a broader entry that encompasses all IMU sensors, e.g. `sensor - inertial measurement unit (IMUS)`
4. Good idea... this could also apply to window and partition closure sensors? Or, if the intention is for it to only apply to door sensors, then maybe a more specific abbreviation like "DOORS" makes more sense?

**Comment by RitaLav** [comment]
1. agree with suggestion
2. exists already (LDS)
3. Agree with suggestion
4. See issue https://github.com/theodi/BDNS/issues/74

**Comment by pisuke** [comment]
Addition of IMUS and LVLS in PR #128
