### ISSUE TITLE
AV Abbreviation Additions

### ISSUE THREAD

**Issue by Snoreledge** [theodi/BDNS#60]
Can we add the following proposals to the BDNS 

AMP	Amplifier
AVCP	audiovisual control panel
AVCAM	AV camera
AVWAP	AV Wireless Access point
DSP	Digital Sound Processor
DA	Distribution Amplifier 
PRO	Projector
TPD	Touch panel display
TX	Transmitter
VC	Video Conference
WP	Wireless Presentation

**Comment by Snoreledge** [comment]
Further Proposals I've noted from another project, we want these to align so take into account when adding to the abbreviations register. 

Amplifiers	AMP
Audio Monitor	AMON
AV Connection Plate	ACP
AV Encoder	AVE
Diplexers	ADM
Equalizers	ADM
Mixers	ADM
Splitters	ADM
Induction-Loop Monitor Receivers	ADE
Induction Loop Pads	ADE
Induction Loop Signal Generators	ADE
Infrared Hearing And Assisted Listening Radiators	ADE
Modulators	ADE
Portable Communicators	ADE
Audio/ Visual Outlets	AVO
Fibre Optic Cable Outlets	AVO
Television Outlets	AVO
AV Switches	AVS
Bluetooth Audio Interface	BAI
Camera Control Unit	CCU
Ceiling Microphone	CMIC
Ceiling Speaker	CSP
Enclosure Speaker	ESP
Landscape Speaker	LSP
Digital Signal Processor	DSP
Digital Signage/IPTV Decoder	DSID
Keypad Controller	KCO
LED LCD Display	LCD
LED Module	LED
Linear Array Microphone	LAM
Music Controller	MCT
PC	AVPC
Pendant Speaker	PSP
Preview Monitor	PMON
Room Booking Panel	RBP
Steerable Array Speaker	SASP
Table Microphone	TMIC
Thin Client Device	TCD
Touch Panel	TPAN
VC Codec	VCC
VC Codec Soundbar	VCCS
VC/Ingest Camera	VCAM
Mute Button	MUT
Matrix Switcher	MSW
Mixing Desk	MIX
Vision Mixer	VMIX
Wireless Microphone	WMIC
Wireless Microphone Receiver	WMR
Wireless Presentation Device	WPD

**Comment by RitaLav** [comment]
We will go ahead and add abbreviations as per table on comment 'Aug 25, 2021'

**Comment by jgunstone** [comment]
I think that some of the above have been added... 
so gonna run through the list and tick off those ones... 

- [ ] **AVEQ** - av equipment
- [ ] **AMP** - av equipment - audio amplifier
- [ ] **AAE** - av equipment - audio assistive equipment
- [ ] **MIC** - av equipment - microphone
- [ ] **AMON** - av equipment - audio monitor
- [ ] **AVO** - av equipment - audio visual outlet
- [ ] **AVE** - av equipment - audio visual encoder
- [ ] **AVS** - av equipment - audio visual switch
- [ ] **BAI** - av equipment - bluetooth audio interface
- [ ] **CCU** - av equipment - camera control unit
- [ ] **AVKP** - av equipment - audio video control keypad
- [ ] **DSP** - av equipment - digital signal processor
- [ ] **DEC** - av equipment - iptv / digital signage decoder
- [ ] **RBP** - av equipment - room booking panel
- [ ] **TPAN** - av equipment - touch panel
- [ ] **CODEC** - av equipment - codec device
- [ ] **TCD** - av equipment - thin client device
- [ ] **MSW** - av equipment - matrix switcher
- [ ] **MIX** - av equipment - audio mixing desk
- [ ] **VMIX** - av equipment - vision mixing desk
- [ ] **WSEND** - av equipment - wireless sender
- [ ] **WRCVR** - av equipment - wireless receiver
- [ ] **WPD** - av equipment - wireless presentation device
- [ ] **ADM** - av equipment - audio mixer / splitter / equalizer / diplexer
- [ ] **DWB** - av equipment - digital whiteboard
- [ ] **DS** - av equipment - display screen
- [ ] **CMS** - av equipment - iptv / digital signage content management system device
- [ ] **NVR** - av equipment - networked video recorder
- [ ] **SPK** - av equipment - speaker
- [ ] **VDW** - av equipment - video wall
- [ ] **BLR** - burner - boiler
- [ ] **FR** - burner - furnace
- [ ] **SB** - burner - steam boiler
- [ ] **CAM** - camera
- [ ] **PTZCAM** - camera - pan tilt zoom camera

**Comment by jgunstone** [comment]
here is the main IFC type used for AV stuff:

https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/schema/ifcelectricaldomain/lexical/ifcaudiovisualappliancetypeenum.htm

**Comment by RitaLav** [comment]
Addressed in pull request #210
