### ISSUE TITLE
Change Specific Asset Abbreviation Categories for FOODEQ

### ISSUE THREAD

**Issue by jamesshawFDT** [theodi/BDNS#65]
Specific asset abbreviation - the list is too specific for some appliances and not inclusive for others. We have a global specification list we work with. It makes sense for us at least if we can group appliances by 'Type of Equipment' (column A) in order we can capture more products.  

We propose the following

ANC | Ancillary
BEV | Beverage
COOK | Cooking
DISH | Dish Room
EQPT | Equipment
MISC | Miscellaneous
MOBL | Mobile Equipment
REFG | Refrigeration
SERV | Serving
STSL | Stainless Steel
VENT | Ventilation
WASTE | Waste Management

**Comment by pisuke** [comment]
Thanks @jamesshawFDT for suggesting these abbreviations.
Unfortunately they don't apply to specific devices or assets, which are the target of the BDNS naming standard.
It would be useful to discuss this in a specific call, so I'll follow up with an invite to get into the details.
Thanks!

**Comment by jamesshawFDT** [comment]
Thanks Francesco, I look forward to connecting.
[image: Google Food]




James Shaw  |  Global Kitchen Design Manager

Google

London, UK  |  +44 7384 915450

**Comment by pisuke** [comment]
@jamesshawFDT Thanks for the help suggesting the new food equipment abbreviations.
I've prepared this pull request #89  with the new abbreviations, can you please have a look before I merge it?
Thanks!

**Comment by jamesshawFDT** [comment]
@pisuke reviewed the list I couldn't find anything of concern. Thanks for the support in developing this list!

**Comment by pisuke** [comment]
Wonderful, I'll merge the PR shortly. Thanks for the help and review @jamesshawFDT!

**Comment by pisuke** [comment]
Addressed in PR #89
