### ISSUE TITLE
Speed Gates Abbreviation

### ISSUE THREAD

**Issue by Snoreledge** [theodi/BDNS#67]
Can speed gates be added to the abbreviations register?

SPDG would be our proposal.

**Comment by RitaLav** [comment]
From weekly meeting:
- ACS (access control system) to be added as new abbreviation
- Speedgates do not need a separate abbreviation (covered by reader, eg RFID reader related abbreviations)

**Comment by pisuke** [comment]
Addition of ACS in PR #128
