### ISSUE TITLE
Dew Point Switch

### ISSUE THREAD

**Issue by richardkreid** [theodi/BDNS#69]
@KenEnright @pisuke 

As per my comments on Frost Protection Switch [https://github.com/theodi/BDNS/issues/68](url)

The 'Dew Point Switch' [https://github.com/theodi/BDNS/blob/master/BDNS_Abbreviations_Register.csv#L6](url) is also too specific. Should this be more of a 'humidistat' or a 'moisture switch' rather than being 'application specific' of switching at 'dew point'.

Thoughts?

**Comment by RitaLav** [comment]
Agree with Richard's point

**Comment by RitaLav** [comment]
Weekly meeting note:

@richardkreid we can find both examples in literature with slightly different applications - would suggest to also add an abbreviation for 'humidistat' for completeness (eg HSTAT)?

**Comment by RitaLav** [comment]
Noting there exists 'HMS - humidity sensor' within the abbreviation register, we will close this issue for now. If needed, please go ahead and reopen.
