### ISSUE TITLE
Need Abbreviation for sensor & system

### ISSUE THREAD

**Issue by Venkiice** [theodi/BDNS#73]
Particulate matter (PM2.5, PM10.0) - PMS
TVOC Sensor -TVOC
Aspirating Smoke Detection -ASD
Battery Monitoring System or Panel -BMP

**Comment by RitaLav** [comment]
for items 1 and 2 - are the sensors only measuring PMS and TVOC respectively? 
If not, suggest using the multi-sensor abbreviation (MTS).

**Comment by RitaLav** [comment]
Please reopen this issue if the abbreviations are still required.
