### ISSUE TITLE
Uniqueness of "asset_description" and/or "asset_abbreviation"

### ISSUE THREAD

**Issue by Jeremy-514** [theodi/BDNS#75]
Specifically :
at time of writing BDNS_Abbreviations_Register.csv contains two identical "asset_description" values ("pump - sewage ejector pump")
and two identical "asset_abbreviation" values ("SE") with "asset_description"s of "sewage ejector" and "pump - sewage ejector pump".

Generally :
I am offering a drop-down list to select and Asset's "BDNS Asset Type", where the list content is derived from BDNS_Abbreviations_Register.csv, not having a guaranteed unique key, that wont change in future versions, is problematic when refreshing the list while retaining the previously selected value.
To solve the uniqueness issue, is it worth authoring the "master" in XML with a simple XSD schema?
Which I would be happy to provide.
The XSD schema could also enforce other restraints e.g. abbreviations are all capitals and 2 to 6 characters long.
I know generating a CSV file from the XML is straight forward but I haven't done it in a while.
The "wont change in future versions" issue is a different matter, my only suggestion is adding an ordinal column, which would then render the uniqueness requirement redundant.

**Comment by pisuke** [comment]
Hi @Jeremy-514 thanks for spotting this. I've updated the sewage ejector (SE) description.
The current idea is to add a validation check using git actions. 
We have a master Google sheet document which has comparisons to other standards like Brick schema and Haystack so some checking can be added also there with App Script.
We could discuss this at the weekly meeting on Wednesday if you can join it. Please drop me a direct message on [my linkedin account](https://www.linkedin.com/in/francescoanselmo/) and I can share the invite.

**Comment by pisuke** [comment]
Short term action, remove SE (sewage ejector)

**Comment by Jeremy-514** [comment]
[bdnsAssetRegister XML & XSD.zip](https://github.com/theodi/BDNS/files/7677316/bdnsAssetRegister.XML.XSD.zip)
If you unzip the attached and then open the xml file with an editor capable of performing XSD validation then the duplicates are revealed. Eclipse does this very well and re-validates dynamically when either file is saved, Notepad++ (with the "XML Tools" plug-in) also works.

**Comment by pisuke** [comment]
SE abbreviation now removed in #89. Thanks @Jeremy-514 for providing the XSD validation example files. I've started working on an automated process based on [GitHub actions](https://github.com/features/actions). More details soon!

**Comment by pisuke** [comment]
I've created a [github actions automated checking workflow](https://github.com/theodi/BDNS/actions/workflows/github-actions-check.yml) that checks for duplicate abbreviations when a pull request is submitted.
You can check the [code of of the program written in python to check for duplicates](https://github.com/theodi/BDNS/blob/master/tools/check-duplicates.py). In the end there was no need to go the XML / XSD route, as the check can be handled directly in the python checking program.
Addressed in #91
