### ISSUE TITLE
Grey Water Packaged System

### ISSUE THREAD

**Issue by TheFridgeShaman** [theodi/BDNS#81]
Grey Water Packaged System – GWS
To be discussed as this system will consist of several elements such as different types of tanks, filtration units, pumps etc

**Comment by RitaLav** [comment]
Makes sense, perhaps some key components could be:
Greywater booster pump (GWBP)
Greywater storage tank (GWT or GWST)
Noting it is a packaged system, it would have a controller for the overall system, so we should have an abbreviation for that too

**Comment by richardkreid** [comment]
I think this is an important one to discuss. In essence I'd question the
value of naming the packaged system. In terms of IoT and monitoring it is
the component parts (as Rita suggested) plus the sensors that are important.

Richard Reid
GEN | EMEA IoT TPM
London
+44 7385 026 679
***@***.***

**Comment by ocbark** [comment]
+ 1 to Richards point. I would favour naming individual items rather than systems

**Comment by RitaLav** [comment]
Meeting 1-Feb: Abbreviations for greywater pump and greywater tank are suggested to be added.

**Comment by RitaLav** [comment]
Addressed in #152
