### ISSUE TITLE
Add PB for UK Panel board

### ISSUE THREAD

**Issue by gerrykou** [theodi/BDNS#87]
PB is used in UK and we need to use it for our projects. What is already suggested for american LVPB is not suitable.

**Comment by noursaidi** [comment]
What is it that makes `LVPB` not suitable?

**Comment by RitaLav** [comment]
Voltage reference from description can be removed.  
Low Voltage and High Voltage can be used in relation to what is classified as Low Voltage or High Voltage in the respective region.

Electrical abbreviations could be reviewed as a whole for alignment across different regions.

**Comment by pisuke** [comment]
Closing as this is discussed in the wider issue #123
