### ISSUE TITLE
Additional Instrumentation

### ISSUE THREAD

**Issue by rossjames-arup** [theodi/BDNS#93]
There are a number of HVAC controls/instrumentation that could be added. Currently known are:
- Pressure sensor given but pressure switch is not.
- Airflow measurement devices (flow sensor generally or venturi meter, flow grid etc specifically)
- Panel mounted user push buttons, there may be other items similar to this that could be added also.
- Liquid level sensors and level switches
- Various gas detection sensors. Gas detection panel is given but this would likely refer to a dedicated panel.

**Comment by pisuke** [comment]
Hi @rossjames-arup can you please create individual asset abbreviation requests using the new issue feature for the ones you think are important?

**Comment by jgunstone** [comment]
just double checked and it looks like these got added at some point... 
- [x] AVFS 
- [x] WVFS 
- [x] SLS (sound level sensor) - does this satisfy the LVLS above?
- [x] FM

so I think this issue can be closed...
