### ISSUE TITLE
PHX query

### ISSUE THREAD

**Issue by john-c-OSS** [theodi/BDNS#96]
Hi - we have a client request for a new abbreviation to show the difference for a plate heat exchanger that is dealing with heating or cooling.  Currently there is PHX - could there be a CPHX of HPHX to differentiate the two?  Thanks in advance!  JC

**Comment by RitaLav** [comment]
This is acceptable.

**Comment by RitaLav** [comment]
@JoyXu08 could you please address this (create a pull request)?

**Comment by pisuke** [comment]
Addressed in #140
