### ISSUE TITLE
request for addition of asset abbreviation in the BDNS

### ISSUE THREAD

**Issue by RathishKJ** [theodi/BDNS#98]
Hello,

There are equipment that are not abbreviated in the BDNS. We are proposing the abbreviations also along with the asset name. Please provide inputs or concurrence to proceed to initiate the pull request for the same.

1.Ceiling Suspended unit--> CSU 
The ceiling suspended unit in regional usage will be identified as CSU even it has the same functionality as that of an FCU. Hence suggesting a new abbreviation for easy identification.

2.Exhaust Dry Scrubber Unit--> DSU
Dry scrubber unit representation is not there in BDNS
3.Air Purifier Unit--> APU
4.Air Washer Unit--> AWSH
5.Vaporizer Panel (used in Gas panel)--> VP
6.Hydrogen Sensor--> HDS
7.Velocity sensor--> VS

Regards,
Rathish KJ

**Comment by RitaLav** [comment]
Point 1: this is also raised in issue 83 - it would be best to be tracked under the same issue.

**Comment by RathishKJ** [comment]
Hi @RitaLav , could you please share the link of the Issue 83. 
Meanwhile, could you please provide your concurrence for the points from 2 to 7.

regards,
Rathish KJ

**Comment by RathishKJ** [comment]
As per the #83, found the 1 Asset abbreviation query answered. request for clarification on the rest

**1. Ceiling Suspended unit--> AHU (as recommended in #83 (https://github.com/theodi/BDNS/issues/83#issuecomment-1008815931)**


3. Exhaust Dry Scrubber Unit--> DSU, Open in #83 , https://github.com/theodi/BDNS/issues/83#issuecomment-1041397896

4. Air Purifier Unit--> APU
5. Air Washer Unit--> AWSH
6. Vaporizer Panel (used in Gas panel)--> VP
7. Hydrogen Sensor--> HDS
8. Velocity sensor--> VS

**Comment by RitaLav** [comment]
9. Is it a packaged system? Could you give some more info?
8. Could you provide some further info?

Overall abbreviations seem reasonable  - @pisuke @richardkreid any further thoughts, or can we add to register?

**Comment by RathishKJ** [comment]
> 9. Is it a packaged system? Could you give some more info?
> 
>     10. Could you provide some further info?
> 
> 
> Overall abbreviations seem reasonable - @pisuke @richardkreid any further thoughts, or can we add to register?

Is it a packaged system? Could you give some more info?
Ratish: It is similar to the packaged system. Here we are doing the pump integration of the solar water heater plant.

**Comment by pisuke** [comment]
They seem reasonable to me.
We have not used the term "plant" or "system" much, trying to avoid it. 
@richardkreid this seems to be a packaged system, should we name it or revert to naming its components instead?

**Comment by RathishKJ** [comment]
> They seem reasonable to me. We have not used the term "plant" or "system" much, trying to avoid it. @richardkreid this seems to be a packaged system, should we name it or revert to naming its components instead?

Also, i would like to add **Liftwell pressurization Fan** as an Asset abbreviated as **ELVPF**.
